name: Generate 3D contribution graph

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D graph
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ShashimalMadhuwantha

      - name: Normalize output filename
        run: |
          ls -la profile-3d-contrib || true
          # Prefer a known theme; fallback to the first SVG found
          for f in profile-3d-contrib/profile-night-rainbow.svg \
                   profile-3d-contrib/profile-gitblock.svg \
                   profile-3d-contrib/profile-green-animate.svg; do
            if [ -f "$f" ]; then
              cp -f "$f" profile-3d-contrib/profile-3d.svg
              break
            fi
          done
          if [ ! -f profile-3d-contrib/profile-3d.svg ]; then
            cp -f "$(ls profile-3d-contrib/*.svg | head -n 1)" profile-3d-contrib/profile-3d.svg
          fi
          ls -la profile-3d-contrib

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}