name: Generate 3D contribution graph

on:
  schedule:
    - cron: "0 0 * * *" # daily at 00:00 UTC
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ShashimalMadhuwantha

      - name: Normalize output filename
        run: |
          set -e
          cd profile-3d-contrib
          target=""
          for f in profile-night-rainbow.svg profile-green-animate.svg profile-season-animate.svg profile-*.svg; do
            if [ -f "$f" ]; then target="$f"; break; fi
          done
          if [ -z "$target" ]; then
            target=$(ls -1 *.svg | head -n 1 || true)
          fi
          if [ -n "$target" ]; then
            cp "$target" profile.svg
          else
            echo "No SVG generated" >&2
            exit 1
          fi

      - name: Publish images to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
